apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.application_name | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    github.com/project-slug: ${{values.destination | dump}}
    backstage.io/techdocs-ref: dir:.
spec:
  type: application
  lifecycle: experimental
  owner: ${{values.owner | dump}}