---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: hngiap
spec:
  memberOf: [admin]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admin
  description: Administrator team
spec:
  type: team
  children: []
